# docker-compose up
# docker-compose run web rake db:migrate db:seed
#
version: '3.6'
services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
        - 8080:8080
  web:
    build: .
    depends_on:
      - db
    command: bundle exec rails s -p 3707 -b '0.0.0.0'
    volumes:
      - .:/opt/rails-api
    ports:
      - "3707:3707"
    environment:
      RAILS_ENV: development
      PGHOST: db
      PGUSER: postgres
      REDIS_URL: redis://redis
  db:
    image: postgres:14-alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_DB: "rails_api_dev"
  redis:
    image: redis:6.0.5-alpine
    ports:
      - 6379:6379
volumes:
  code:
  database:

# Define synchronization and forwarding sessions
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "."
      beta: "volume://code"
      mode: "two-way-resolved"
